config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :articles do
    resources :comments
  end

  get 'login', to: 'user_authenticator#login'
  get 'logout', to: 'user_authenticator#logout'
  post 'authenticate', to: 'user_authenticator#authenticate'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :article, presence: true

  scope :last_ten, -> { order(created_at: :desc).limit(10) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, presence: true

  scope :last_ten, -> { order(created_at: :desc).limit(10) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_user_session, only: [:new, :edit, :create, :delete]

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Articolo inserito'
    else
      flash[:notice] = "Attenzione! E' necessario compilare tutti i campi."
      render 'new'
    end
  end

  def index
    @articles = Article.all
  end

  private

  def article_params
    params.require(:article).permit(:title, :article)
  end

  def check_user_session
    return if session[:user_id]
    flash[:notice] = 'Devi fare il login per continuare'
    redirect_to :login
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = Comment.new(comment_params)
    @article.comments.append(@comment)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Commento inserito.' }
      else
        flash[:notice] = "Attenzione! E' necessario inserire un commento."
        format.html { render 'articles/show' }
      end
      format.js
    end
  end

  def index
    redirect_to Article.find(params[:article_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/user_authenticator_controller.rb
class UserAuthenticatorController < ApplicationController
  def login
    render 'logout' if check_user_session
  end

  def authenticate
    if user_params[:username] == 'dottorx' && user_params[:password] == 'dottorx'
      session[:user_id] = user_params[:username]
      redirect_to :root
    else
      flash.now[:notice] = 'Autenticazione errata'
      render 'login'
    end
  end

  def logout
    if check_user_session
      session[:user_id] = nil
      redirect_to :root
    else
      redirect_to :login
    end
  end

  private

  def check_user_session
    session[:user_id]
  end

  def user_params
    params.permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @comments = Comment.last_ten
    @articles = Article.last_ten
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/user_authenticator_helper.rb
module UserAuthenticatorHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<b><%= article.title %></b> <br>

<%= article.article %> <br>

app/views/articles/index.html.erb
  <%= render @articles %>

app/views/articles/new.html.erb
<div id='article-form'>
<%= form_for @article do |f| %>
  <br>
    <%= f.label :title, "Titolo" %>
    <br>
  <%= f.text_field :title %>
 <br>
  <%= f.label :article, "Articolo"%>
  <br>
  <%= f.text_area :article %>

<br>
  <%= f.submit 'Crea articolo' %>

<% end %>

</div>

app/views/articles/show.html.erb
<div id="article" class="w3-display-container">
<%= render @article %>
</div>
<div id="comments">
<%= render @article.comments %>
</div>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% if comment.id %>
<%= content_tag :div, id: dom_id(comment) do %>
<b>Commento:</b> <%= comment.body %>
<% end %>

<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build], html: {id: "form"}) do |f| %>
  <%= f.label :body, "Commenta: " %> <br>
  <%= f.text_field :body %> <%= f.submit "Commenta" %>
<% end %>

app/views/comments/create.js.erb
<% if @comment.new_record? %>
  $('form').effect('highlight', {color:'red'});
<% else %>
  $('div#comments').append(" <%= escape_javascript(render @comment) %>");
  $('div#<%= dom_id(@comment) %>').effect('highlight');
  $("input[name='comment[body]']").val("");
<% end %>

app/views/layouts/_flash_viewer.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/menu' %>
    <%= render 'layouts/flash_viewer' %>
    <div class="w3-display-topleft" style="max-width:800px;margin-top:100px;margin-left:20px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", welcome_index_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Placeholder</a>
      </li>
  </div>
</nav>

app/views/user_authenticator/login.html.erb
<%= form_tag authenticate_path do  %>
  <%= label_tag :username, "User" %>
  <%= text_field_tag :username %>
  <%= label_tag :password, "Password" %>
  <%= password_field_tag :password %>
  <%= submit_tag 'Login' %>
<% end %>

app/views/user_authenticator/logout.html.erb
Sei loggato come <%= session[:user_id] %>. <%= link_to 'Logout', controller: 'user_authenticator', action: 'logout' %>

app/views/welcome/index.html.erb
<h1>Benvenuto nel mio blog!</h1>

<p>Ultimi 10 articoli</p>
<% @articles.each do |a| %>
<b>
  <%= a.title %> </b>
  <br>
  <%= a.article %>
  <br>
  <%= link_to "Leggi", a %> Commenti: <%= a.comments.size %>
  <hr>
<% end %>